import { Entity, PrimaryGeneratedColumn, Column, ManyToOne } from "typeorm";
import { Wallet } from "./wallet.model"; // Import the Wallet entity

@Entity()
export class TransactionHistory {
    @PrimaryGeneratedColumn()
    id?: number;  // Auto-generated by TypeORM

    @ManyToOne(() => Wallet, (wallet) => wallet.transactions)
    id_wallet: Wallet;

    @Column("date")
    date: Date;

    @Column("float")
    transaction_amount: number;

    @Column()
    status: string;

    @Column("float")
    resulted_balance: number;

    constructor(id_wallet: Wallet, transaction_amount: number = 0, status: string = '', resulted_balance: number = 0) {
        this.id_wallet = id_wallet;  // Wallet instance must be passed during initialization
        this.date = new Date();  // Default to current date
        this.transaction_amount = transaction_amount;  // Default value for transaction amount
        this.status = status;  // Default value for status (successful/unsuccessful)
        this.resulted_balance = resulted_balance;  // Default value for resulted balance
    }
}
